github:
  username: ${{ secrets.JAVA_GITHUB_USERNAME }}
  token:    ${{ secrets.JAVA_GITHUB_TOKEN }}

codeowners:
- path:  "*"
  owner: "garethjevans"
- path:  "*"
  owner: "samcolson4"

package:
  repository:     ghcr.io/garethjevans/apache-tomee
  register:       true
  registry_token: ${{ secrets.JAVA_GITHUB_TOKEN }}

docker_credentials:
- registry: ghcr.io
  username: ${{ github.actor }}
  password: ${{ secrets.JAVA_GITHUB_TOKEN }}

dependencies:
- name:            Tomee 7
  id:              tomee
  version_pattern: "7\\.[\\d]+\\.[\\d]+"
  uses:            docker://garethjevans/tomee-dependency:main
  with:
    uri: https://downloads.apache.org/tomee
    dist: microprofile
    major: 7
- name:            Tomee 8
  id:              tomee
  version_pattern: "8\\.[\\d]+\\.[\\d]+"
  uses:            docker://garethjevans/tomee-dependency:main
  with:
    uri: https://downloads.apache.org/tomee
    dist: microprofile
    major: 8
- name:            Tomee 9
  id:              tomee
  version_pattern: "9\\.[\\d]+\\.[\\d]+?[-+]?[a-zA-Z0-9]+"
  uses:            docker://garethjevans/tomee-dependency:main
  with:
    uri: https://downloads.apache.org/tomee
    dist: microprofile
    major: 9
- id:   tomcat-access-logging-support
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo.spring.io/release
    group_id:    org.cloudfoundry
    artifact_id: tomcat-access-logging-support
- id:   tomcat-lifecycle-support
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo.spring.io/release
    group_id:    org.cloudfoundry
    artifact_id: tomcat-lifecycle-support
- id:   tomcat-logging-support
  uses: docker://ghcr.io/paketo-buildpacks/actions/maven-dependency:main
  with:
    uri:         https://repo.spring.io/release
    group_id:    org.cloudfoundry
    artifact_id: tomcat-logging-support
