schemaVersion: 2.0.0
fileExistenceTests:
  - name: 'access-logging-support'
    path: '/layers/garethjevans_apache-tomcat/helper/exec.d/access-logging-support'
    shouldExist: true
    permissions: 'Lrwxrwxrwx'

  - name: 'managed-datasource-support'
    path: '/layers/garethjevans_apache-tomcat/helper/exec.d/managed-datasource-support'
    shouldExist: true
    permissions: 'Lrwxrwxrwx'

  - name: 'postgres-jar'
    path: '/layers/garethjevans_apache-tomcat/catalina-base/lib/postgresql-42.3.1.jar'
    shouldExist: true
    permissions: '-rw-r--r--'

  - name: 'binding-test'
    path: '/bindings/postgresql/type'
    shouldExist: false
    permissions: '-rw-r--r--'
